### PR TITLE
chore(deps): upgrade typescript to v6.0.3

### PR DESCRIPTION
**Pull request by BallLightningAB**
TypeScript 6.0 changes the default value of the `strict` flag from false to true, deprecates ES3/ES5 targets, and deprecates `import assert` in favor of `import with`.

**Changes:**
- Upgraded typescript from 5.9.3 to 6.0.3
- Added `ignoreDeprecations: "6.0"` to tsconfig.json to suppress deprecation warnings

**Note:** The project already has `strict: true` in tsconfig.json, so the default change has no impact. The `ignoreDeprecations` flag allows a gradual migration to new syntax patterns.

### CODE REVIEW

**Comment by BallLightningAB** [comment]
## PR Research Summary

**What this PR does:**
- Upgrades typescript from 5.9.3 to 6.0.3
- Adds `ignoreDeprecations: "6.0"` to tsconfig.json to suppress deprecation warnings
- Project already has `strict: true`, so the default strict mode change has no impact

**Current status:**
- ✅ gitleaks: passed
- ✅ Vercel Preview Comments: passed
- Files changed: 2 (package.json, tsconfig.json)

**Potential issues to investigate:**
- You mentioned deployment failed - check Vercel preview deployment logs for TypeScript compilation errors
- The `ignoreDeprecations` flag is a temporary measure - eventually need to migrate from deprecated patterns (e.g., `import assert` → `import with`)
- Verify the build still works with TypeScript 6.0

**What needs to be done:**
1. Check Vercel deployment logs for any TypeScript errors
2. Run `pnpm typecheck` locally to verify no new type errors
3. If build works, this PR is ready to merge
4. Consider creating a follow-up task to migrate deprecated syntax patterns when time allows

**Comment by BallLightningAB** [comment]
Superseded by TypeScript 7.0.2 already in `main` (9237abe). Closing this v6 proposal.
